name: hello-test

services:
  db:
    image: postgres:16.3-alpine
    container_name: hello-test-postgres-16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      postgres -c 'max_connections=500'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  redis:
    image: redis:7.2.5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
  hello-test-app:
    build: . 
    command: ./bin/rails server
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app_storage:/rails/storage
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

volumes:
  postgres_data: {}
  app_storage: {}
  redis_data: {}