name: hello-test

services:
  db:
    image: postgres:16.3-alpine
    container_name: hello-test-postgres-16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      postgres -c 'max_connections=500'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  db-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://hello_user:supersecretpassword123@db:5432/hello_test_db_production?sslmode=disable"
    links:
      - db
      - prometheus

  redis:
    image: redis:7.2.5
    command: "redis-server --requirepass password"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
  redis-exporter:
    image: oliver006/redis_exporter
    command:
      - '--redis.password=password'
    ports:
      - "9121:9121"
    restart: unless-stopped
    environment:
      - REDIS_ADDR=redis:6379
    links:
      - redis
      - prometheus
  hello-test-app:
    build: . 
    command: ./bin/rails server
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app_storage:/rails/storage
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.53.1
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana:9.5.20
    ports:
      - "3001:3000"

volumes:
  postgres_data: {}
  app_storage: {}
  redis_data: {}