global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rails'
    static_configs:
      - targets: ['hello-test-app:3000']
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
