global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'rails'
    static_configs:
      - targets: ['hello-test-app:3000']
  - job_name: 'db-exporter'
    static_configs:
      - targets: ['db-exporter:9187']
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
