{
 "title": "Rails Application Dashboard",
 "tags": [
  "rails",
  "app",
  "stats"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Server Requests Totals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_server_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum[5m])/rate(http_server_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_server_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}